// Generated by CoffeeScript 1.6.3
(function() {
  var chatModule;

  chatModule = angular.module("chat", []);

  chatModule.controller('ChatHallCtrl', function($scope) {
    $scope.connectedChatters = [];
    $scope.joined = false;
    $scope.connectedChatters.push('Tester');
    $scope.connectedChatters.push('Anny');
    return $scope.join = function() {
      return $scope.joined = true;
    };
  });

}).call(this);
